#############################################################################
# Makefile for building: libqtgeoservices_offline.so
# Generated by qmake (2.01a) (Qt 4.7.4) on: Mo 15. Okt 12:26:36 2012
# Project:  qtgeoservices_offline.pro
# Template: lib
# Command: c:/qtsdk/1.2.1/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe -spec c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile qtgeoservices_offline.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -Wno-psabi -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -Wno-psabi -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -Ic:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -I. -Ic:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtCore -Ic:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtGui -Ic:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -Ic:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtLocation -Iquazip-0.3/quazip -Ic:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -Ic:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtMobility -Imoc
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,D:/usr/lib -shared
LIBS          = $(SUBLIBS)  -LC:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib -L/usr/lib -lQtLocation -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = c:/qtsdk/1.2.1/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = qgeomapreply_osz.cpp \
		qgeomapreply_sqlite.cpp \
		qgeomappingmanagerengine_offline.cpp \
		qgeoserviceproviderplugin_offline.cpp \
		quazip-0.3/quazip/ioapi.c \
		quazip-0.3/quazip/unzip.c \
		quazip-0.3/quazip/zip.c \
		quazip-0.3/quazip/quaadler32.cpp \
		quazip-0.3/quazip/quazip.cpp \
		quazip-0.3/quazip/quacrc32.cpp \
		quazip-0.3/quazip/quazipnewinfo.cpp \
		quazip-0.3/quazip/quazipfile.cpp moc/moc_qgeomapreply_osz.cpp \
		moc/moc_qgeomapreply_sqlite.cpp \
		moc/moc_qgeomappingmanagerengine_offline.cpp \
		moc/moc_qgeoserviceproviderplugin_offline.cpp \
		moc/moc_quazipfile.cpp \
		rcc/qrc_qtgeoservices_offline.cpp
OBJECTS       = obj/qgeomapreply_osz.o \
		obj/qgeomapreply_sqlite.o \
		obj/qgeomappingmanagerengine_offline.o \
		obj/qgeoserviceproviderplugin_offline.o \
		obj/ioapi.o \
		obj/unzip.o \
		obj/zip.o \
		obj/quaadler32.o \
		obj/quazip.o \
		obj/quacrc32.o \
		obj/quazipnewinfo.o \
		obj/quazipfile.o \
		obj/moc_qgeomapreply_osz.o \
		obj/moc_qgeomapreply_sqlite.o \
		obj/moc_qgeomappingmanagerengine_offline.o \
		obj/moc_qgeoserviceproviderplugin_offline.o \
		obj/moc_quazipfile.o \
		obj/qrc_qtgeoservices_offline.o
DIST          = c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		qtgeoservices_offline.pro
QMAKE_TARGET  = qtgeoservices_offline
DESTDIR       = 
TARGET        = libqtgeoservices_offline.so
TARGETD       = libqtgeoservices_offline.so

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  $(TARGET)

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)



Makefile: qtgeoservices_offline.pro  c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default/qmake.conf c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl \
		c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl
	$(QMAKE) -spec c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile qtgeoservices_offline.pro
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl:
c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec c:/QtSDK/1.2.1/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile qtgeoservices_offline.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/qtgeoservices_offline1.0.0 || $(MKDIR) obj/qtgeoservices_offline1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/qtgeoservices_offline1.0.0/ && $(COPY_FILE) --parents qgeomapreply_osz.h qgeomapreply_sqlite.h qgeomappingmanagerengine_offline.h qgeoserviceproviderplugin_offline.h debug_offline.h quazip-0.3/quazip/crypt.h quazip-0.3/quazip/quachecksum32.h quazip-0.3/quazip/quazipfileinfo.h quazip-0.3/quazip/quazipnewinfo.h quazip-0.3/quazip/zip.h quazip-0.3/quazip/ioapi.h quazip-0.3/quazip/quacrc32.h quazip-0.3/quazip/quaadler32.h quazip-0.3/quazip/quazipfile.h quazip-0.3/quazip/quazip.h quazip-0.3/quazip/unzip.h obj/qtgeoservices_offline1.0.0/ && $(COPY_FILE) --parents qtgeoservices_offline.qrc obj/qtgeoservices_offline1.0.0/ && $(COPY_FILE) --parents qgeomapreply_osz.cpp qgeomapreply_sqlite.cpp qgeomappingmanagerengine_offline.cpp qgeoserviceproviderplugin_offline.cpp quazip-0.3/quazip/ioapi.c quazip-0.3/quazip/unzip.c quazip-0.3/quazip/zip.c quazip-0.3/quazip/quaadler32.cpp quazip-0.3/quazip/quazip.cpp quazip-0.3/quazip/quacrc32.cpp quazip-0.3/quazip/quazipnewinfo.cpp quazip-0.3/quazip/quazipfile.cpp obj/qtgeoservices_offline1.0.0/ && (cd `dirname obj/qtgeoservices_offline1.0.0` && $(TAR) qtgeoservices_offline1.0.0.tar qtgeoservices_offline1.0.0 && $(COMPRESS) qtgeoservices_offline1.0.0.tar) && $(MOVE) `dirname obj/qtgeoservices_offline1.0.0`/qtgeoservices_offline1.0.0.tar.gz . && $(DEL_FILE) -r obj/qtgeoservices_offline1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_qgeomapreply_osz.cpp moc/moc_qgeomapreply_sqlite.cpp moc/moc_qgeomappingmanagerengine_offline.cpp moc/moc_qgeoserviceproviderplugin_offline.cpp moc/moc_quazipfile.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_qgeomapreply_osz.cpp moc/moc_qgeomapreply_sqlite.cpp moc/moc_qgeomappingmanagerengine_offline.cpp moc/moc_qgeoserviceproviderplugin_offline.cpp moc/moc_quazipfile.cpp
moc/moc_qgeomapreply_osz.cpp: qgeomapreply_osz.h
	C:/QtSDK/1.2.1/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) qgeomapreply_osz.h -o moc/moc_qgeomapreply_osz.cpp

moc/moc_qgeomapreply_sqlite.cpp: qgeomapreply_sqlite.h
	C:/QtSDK/1.2.1/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) qgeomapreply_sqlite.h -o moc/moc_qgeomapreply_sqlite.cpp

moc/moc_qgeomappingmanagerengine_offline.cpp: qgeoserviceproviderplugin_offline.h \
		qgeomappingmanagerengine_offline.h
	C:/QtSDK/1.2.1/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) qgeomappingmanagerengine_offline.h -o moc/moc_qgeomappingmanagerengine_offline.cpp

moc/moc_qgeoserviceproviderplugin_offline.cpp: qgeoserviceproviderplugin_offline.h
	C:/QtSDK/1.2.1/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) qgeoserviceproviderplugin_offline.h -o moc/moc_qgeoserviceproviderplugin_offline.cpp

moc/moc_quazipfile.cpp: quazip-0.3/quazip/quazip.h \
		quazip-0.3/quazip/zip.h \
		quazip-0.3/quazip/ioapi.h \
		quazip-0.3/quazip/unzip.h \
		quazip-0.3/quazip/quazipfileinfo.h \
		quazip-0.3/quazip/quazipnewinfo.h \
		quazip-0.3/quazip/quazipfile.h
	C:/QtSDK/1.2.1/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) quazip-0.3/quazip/quazipfile.h -o moc/moc_quazipfile.cpp

compiler_rcc_make_all: rcc/qrc_qtgeoservices_offline.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc/qrc_qtgeoservices_offline.cpp
rcc/qrc_qtgeoservices_offline.cpp: qtgeoservices_offline.qrc \
		resources/tile_notavailable.png \
		resources/tile_working.png \
		resources/tile_error.png \
		resources/tile_ziperror.png
	c:/QtSDK/1.2.1/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/rcc.exe -name qtgeoservices_offline qtgeoservices_offline.qrc -o rcc/qrc_qtgeoservices_offline.cpp

compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

obj/qgeomapreply_osz.o: qgeomapreply_osz.cpp qgeomapreply_osz.h \
		debug_osz.h \
		qgeomappingmanagerengine_offline.h \
		qgeoserviceproviderplugin_offline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qgeomapreply_osz.o qgeomapreply_osz.cpp

obj/qgeomapreply_sqlite.o: qgeomapreply_sqlite.cpp qgeomapreply_sqlite.h \
		debug_osz.h \
		qgeomappingmanagerengine_offline.h \
		qgeoserviceproviderplugin_offline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qgeomapreply_sqlite.o qgeomapreply_sqlite.cpp

obj/qgeomappingmanagerengine_offline.o: qgeomappingmanagerengine_offline.cpp qgeomappingmanagerengine_offline.h \
		qgeoserviceproviderplugin_offline.h \
		qgeomapreply_osz.h \
		qgeomapreply_sqlite.h \
		debug_osz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qgeomappingmanagerengine_offline.o qgeomappingmanagerengine_offline.cpp

obj/qgeoserviceproviderplugin_offline.o: qgeoserviceproviderplugin_offline.cpp qgeoserviceproviderplugin_offline.h \
		qgeomappingmanagerengine_offline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qgeoserviceproviderplugin_offline.o qgeoserviceproviderplugin_offline.cpp

obj/ioapi.o: quazip-0.3/quazip/ioapi.c quazip-0.3/quazip/ioapi.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/ioapi.o quazip-0.3/quazip/ioapi.c

obj/unzip.o: quazip-0.3/quazip/unzip.c quazip-0.3/quazip/unzip.h \
		quazip-0.3/quazip/ioapi.h \
		quazip-0.3/quazip/crypt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/unzip.o quazip-0.3/quazip/unzip.c

obj/zip.o: quazip-0.3/quazip/zip.c quazip-0.3/quazip/zip.h \
		quazip-0.3/quazip/ioapi.h \
		quazip-0.3/quazip/crypt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/zip.o quazip-0.3/quazip/zip.c

obj/quaadler32.o: quazip-0.3/quazip/quaadler32.cpp quazip-0.3/quazip/quaadler32.h \
		quazip-0.3/quazip/quachecksum32.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/quaadler32.o quazip-0.3/quazip/quaadler32.cpp

obj/quazip.o: quazip-0.3/quazip/quazip.cpp quazip-0.3/quazip/quazip.h \
		quazip-0.3/quazip/zip.h \
		quazip-0.3/quazip/ioapi.h \
		quazip-0.3/quazip/unzip.h \
		quazip-0.3/quazip/quazipfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/quazip.o quazip-0.3/quazip/quazip.cpp

obj/quacrc32.o: quazip-0.3/quazip/quacrc32.cpp quazip-0.3/quazip/quacrc32.h \
		quazip-0.3/quazip/quachecksum32.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/quacrc32.o quazip-0.3/quazip/quacrc32.cpp

obj/quazipnewinfo.o: quazip-0.3/quazip/quazipnewinfo.cpp quazip-0.3/quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/quazipnewinfo.o quazip-0.3/quazip/quazipnewinfo.cpp

obj/quazipfile.o: quazip-0.3/quazip/quazipfile.cpp quazip-0.3/quazip/quazipfile.h \
		quazip-0.3/quazip/quazip.h \
		quazip-0.3/quazip/zip.h \
		quazip-0.3/quazip/ioapi.h \
		quazip-0.3/quazip/unzip.h \
		quazip-0.3/quazip/quazipfileinfo.h \
		quazip-0.3/quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/quazipfile.o quazip-0.3/quazip/quazipfile.cpp

obj/moc_qgeomapreply_osz.o: moc/moc_qgeomapreply_osz.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qgeomapreply_osz.o moc/moc_qgeomapreply_osz.cpp

obj/moc_qgeomapreply_sqlite.o: moc/moc_qgeomapreply_sqlite.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qgeomapreply_sqlite.o moc/moc_qgeomapreply_sqlite.cpp

obj/moc_qgeomappingmanagerengine_offline.o: moc/moc_qgeomappingmanagerengine_offline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qgeomappingmanagerengine_offline.o moc/moc_qgeomappingmanagerengine_offline.cpp

obj/moc_qgeoserviceproviderplugin_offline.o: moc/moc_qgeoserviceproviderplugin_offline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qgeoserviceproviderplugin_offline.o moc/moc_qgeoserviceproviderplugin_offline.cpp

obj/moc_quazipfile.o: moc/moc_quazipfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_quazipfile.o moc/moc_quazipfile.cpp

obj/qrc_qtgeoservices_offline.o: rcc/qrc_qtgeoservices_offline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_qtgeoservices_offline.o rcc/qrc_qtgeoservices_offline.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/qtgeoservices_offline/lib/ || $(MKDIR) $(INSTALL_ROOT)/opt/qtgeoservices_offline/lib/ 
	-$(INSTALL_PROGRAM) "$(TARGET)" "$(INSTALL_ROOT)/opt/qtgeoservices_offline/lib/$(TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/qtgeoservices_offline/lib/$(TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/qtgeoservices_offline/lib/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

