#############################################################################
# Makefile for building: libqtgeoservices_sqlite.so
# Generated by qmake (2.01a) (Qt 4.7.4) on: Mi 31. Okt 20:43:06 2012
# Project:  qt-mobility-geoservice-sqlite.pro
# Template: lib
# Command: c:/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe -spec c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile qt-mobility-geoservice-sqlite.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -Wno-psabi -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -Wno-psabi -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -Ic:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -I. -Ic:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtCore -Ic:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtGui -Ic:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtSql -Ic:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -Ic:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtLocation -Ic:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -Ic:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtMobility -Imoc
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,D:/usr/lib -shared
LIBS          = $(SUBLIBS)  -LC:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib -L/usr/lib -lQtLocation -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = c:/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = qgeomapreply_sqlite.cpp \
		qgeomappingmanagerengine_sqlite.cpp \
		qgeoserviceproviderplugin_sqlite.cpp moc/moc_qgeomapreply_sqlite.cpp \
		moc/moc_qgeomappingmanagerengine_sqlite.cpp \
		moc/moc_qgeoserviceproviderplugin_sqlite.cpp \
		rcc/qrc_qt-mobility-geoservice-sqlite.cpp
OBJECTS       = obj/qgeomapreply_sqlite.o \
		obj/qgeomappingmanagerengine_sqlite.o \
		obj/qgeoserviceproviderplugin_sqlite.o \
		obj/moc_qgeomapreply_sqlite.o \
		obj/moc_qgeomappingmanagerengine_sqlite.o \
		obj/moc_qgeoserviceproviderplugin_sqlite.o \
		obj/qrc_qt-mobility-geoservice-sqlite.o
DIST          = c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		qt-mobility-geoservice-sqlite.pro
QMAKE_TARGET  = qtgeoservices_sqlite
DESTDIR       = 
TARGET        = libqtgeoservices_sqlite.so
TARGETD       = libqtgeoservices_sqlite.so

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  $(TARGET)

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)



Makefile: qt-mobility-geoservice-sqlite.pro  c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default/qmake.conf c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtSql.prl \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl
	$(QMAKE) -spec c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile qt-mobility-geoservice-sqlite.pro
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtSql.prl:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile qt-mobility-geoservice-sqlite.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/qtgeoservices_sqlite1.0.0 || $(MKDIR) obj/qtgeoservices_sqlite1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/qtgeoservices_sqlite1.0.0/ && $(COPY_FILE) --parents qgeomapreply_sqlite.h qgeomappingmanagerengine_sqlite.h qgeoserviceproviderplugin_sqlite.h debug_sqlite.h obj/qtgeoservices_sqlite1.0.0/ && $(COPY_FILE) --parents qt-mobility-geoservice-sqlite.qrc obj/qtgeoservices_sqlite1.0.0/ && $(COPY_FILE) --parents qgeomapreply_sqlite.cpp qgeomappingmanagerengine_sqlite.cpp qgeoserviceproviderplugin_sqlite.cpp obj/qtgeoservices_sqlite1.0.0/ && (cd `dirname obj/qtgeoservices_sqlite1.0.0` && $(TAR) qtgeoservices_sqlite1.0.0.tar qtgeoservices_sqlite1.0.0 && $(COMPRESS) qtgeoservices_sqlite1.0.0.tar) && $(MOVE) `dirname obj/qtgeoservices_sqlite1.0.0`/qtgeoservices_sqlite1.0.0.tar.gz . && $(DEL_FILE) -r obj/qtgeoservices_sqlite1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_qgeomapreply_sqlite.cpp moc/moc_qgeomappingmanagerengine_sqlite.cpp moc/moc_qgeoserviceproviderplugin_sqlite.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_qgeomapreply_sqlite.cpp moc/moc_qgeomappingmanagerengine_sqlite.cpp moc/moc_qgeoserviceproviderplugin_sqlite.cpp
moc/moc_qgeomapreply_sqlite.cpp: qgeomapreply_sqlite.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) qgeomapreply_sqlite.h -o moc/moc_qgeomapreply_sqlite.cpp

moc/moc_qgeomappingmanagerengine_sqlite.cpp: qgeoserviceproviderplugin_sqlite.h \
		qgeomappingmanagerengine_sqlite.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) qgeomappingmanagerengine_sqlite.h -o moc/moc_qgeomappingmanagerengine_sqlite.cpp

moc/moc_qgeoserviceproviderplugin_sqlite.cpp: qgeoserviceproviderplugin_sqlite.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) qgeoserviceproviderplugin_sqlite.h -o moc/moc_qgeoserviceproviderplugin_sqlite.cpp

compiler_rcc_make_all: rcc/qrc_qt-mobility-geoservice-sqlite.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc/qrc_qt-mobility-geoservice-sqlite.cpp
rcc/qrc_qt-mobility-geoservice-sqlite.cpp: qt-mobility-geoservice-sqlite.qrc \
		resources/tile_notavailable.png \
		resources/tile_working.png
	c:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/rcc.exe -name qt-mobility-geoservice-sqlite qt-mobility-geoservice-sqlite.qrc -o rcc/qrc_qt-mobility-geoservice-sqlite.cpp

compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

obj/qgeomapreply_sqlite.o: qgeomapreply_sqlite.cpp qgeomapreply_sqlite.h \
		debug_sqlite.h \
		qgeomappingmanagerengine_sqlite.h \
		qgeoserviceproviderplugin_sqlite.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qgeomapreply_sqlite.o qgeomapreply_sqlite.cpp

obj/qgeomappingmanagerengine_sqlite.o: qgeomappingmanagerengine_sqlite.cpp qgeomappingmanagerengine_sqlite.h \
		qgeoserviceproviderplugin_sqlite.h \
		qgeomapreply_sqlite.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qgeomappingmanagerengine_sqlite.o qgeomappingmanagerengine_sqlite.cpp

obj/qgeoserviceproviderplugin_sqlite.o: qgeoserviceproviderplugin_sqlite.cpp qgeoserviceproviderplugin_sqlite.h \
		qgeomappingmanagerengine_sqlite.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qgeoserviceproviderplugin_sqlite.o qgeoserviceproviderplugin_sqlite.cpp

obj/moc_qgeomapreply_sqlite.o: moc/moc_qgeomapreply_sqlite.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qgeomapreply_sqlite.o moc/moc_qgeomapreply_sqlite.cpp

obj/moc_qgeomappingmanagerengine_sqlite.o: moc/moc_qgeomappingmanagerengine_sqlite.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qgeomappingmanagerengine_sqlite.o moc/moc_qgeomappingmanagerengine_sqlite.cpp

obj/moc_qgeoserviceproviderplugin_sqlite.o: moc/moc_qgeoserviceproviderplugin_sqlite.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qgeoserviceproviderplugin_sqlite.o moc/moc_qgeoserviceproviderplugin_sqlite.cpp

obj/qrc_qt-mobility-geoservice-sqlite.o: rcc/qrc_qt-mobility-geoservice-sqlite.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_qt-mobility-geoservice-sqlite.o rcc/qrc_qt-mobility-geoservice-sqlite.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/qtgeoservices_sqlite/lib/ || $(MKDIR) $(INSTALL_ROOT)/opt/qtgeoservices_sqlite/lib/ 
	-$(INSTALL_PROGRAM) "$(TARGET)" "$(INSTALL_ROOT)/opt/qtgeoservices_sqlite/lib/$(TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/qtgeoservices_sqlite/lib/$(TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/qtgeoservices_sqlite/lib/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

